export {default as Login } from "./login/login"
export {default as SignUp } from "./Signup/Signup"
export {default as home} from "./dashboard/dashboard"
export {default as editprofile} from "./editprofile/editprofile"
export {default as profile} from "./profile/profile"